from __future__ import annotations


DEFAULT_SCENARIO = {
    "name": "MIT Sandbox Baseline",
    "description": "Shared-resource import/export terminal sandbox with fill-based stacking delays.",
    "horizon_hours": 120,
    "drain_hours": 24,
    "random_seed": 42,
    "vessel_delay_hours": {"minimum": -2.0, "mode": 1.0, "maximum": 4.0},
    "resources": {
        "berths": 2,
        "sts_cranes": 4,
        "yard_equipment": 5,
        "gate_lanes": 4,
        "rail_slots": 1,
    },
    "gate_calendar": {"open_hour": 6, "close_hour": 18},
    "rail": {
        "import_departures_per_day": 3,
        "train_capacity": 45,
        "train_load_minutes": 90,
        "export_receive_minutes": {"minimum": 35.0, "mode": 45.0, "maximum": 70.0},
    },
    "yard_policy": {
        "putaway_minutes": 18.0,
        "prestage_minutes": 20.0,
        "base_retrieve_minutes": 16.0,
        "reshuffle_minutes": 10.0,
        "alpha_putaway": 0.45,
        "beta_retrieval": 1.2,
        "congestion_threshold": 0.72,
    },
    "yard_blocks": [
        {"id": "standard", "label": "Standard Block", "capacity_teu": 240, "max_stack_height": 5},
        {"id": "reefer", "label": "Reefer Block", "capacity_teu": 60, "max_stack_height": 4},
        {"id": "hazardous", "label": "Hazardous Block", "capacity_teu": 40, "max_stack_height": 3},
    ],
    "container_types": [
        {
            "id": "standard",
            "label": "Standard",
            "block_id": "standard",
            "initial_import_units": 70,
            "initial_export_ready_units": 10,
            "import_truck_share": 0.72,
            "export_truck_share": 0.68,
            "import_release_delay_hours": {"minimum": 8.0, "mode": 16.0, "maximum": 30.0},
            "export_arrival_lead_hours": {"minimum": 10.0, "mode": 18.0, "maximum": 34.0},
            "gate_in_minutes": {"minimum": 9.0, "mode": 12.0, "maximum": 18.0},
            "gate_out_minutes": {"minimum": 11.0, "mode": 14.0, "maximum": 20.0},
            "discharge_minutes": {"minimum": 5.0, "mode": 6.0, "maximum": 8.0},
            "load_minutes": {"minimum": 5.0, "mode": 6.0, "maximum": 8.0},
        },
        {
            "id": "reefer",
            "label": "Reefer",
            "block_id": "reefer",
            "initial_import_units": 18,
            "initial_export_ready_units": 4,
            "import_truck_share": 0.85,
            "export_truck_share": 0.78,
            "import_release_delay_hours": {"minimum": 5.0, "mode": 12.0, "maximum": 20.0},
            "export_arrival_lead_hours": {"minimum": 8.0, "mode": 14.0, "maximum": 24.0},
            "gate_in_minutes": {"minimum": 10.0, "mode": 13.0, "maximum": 19.0},
            "gate_out_minutes": {"minimum": 12.0, "mode": 16.0, "maximum": 24.0},
            "discharge_minutes": {"minimum": 6.0, "mode": 7.0, "maximum": 9.0},
            "load_minutes": {"minimum": 6.0, "mode": 7.0, "maximum": 9.0},
        },
        {
            "id": "hazardous",
            "label": "Hazardous",
            "block_id": "hazardous",
            "initial_import_units": 10,
            "initial_export_ready_units": 2,
            "import_truck_share": 0.9,
            "export_truck_share": 0.85,
            "import_release_delay_hours": {"minimum": 6.0, "mode": 18.0, "maximum": 30.0},
            "export_arrival_lead_hours": {"minimum": 12.0, "mode": 20.0, "maximum": 32.0},
            "gate_in_minutes": {"minimum": 12.0, "mode": 16.0, "maximum": 24.0},
            "gate_out_minutes": {"minimum": 14.0, "mode": 18.0, "maximum": 28.0},
            "discharge_minutes": {"minimum": 7.0, "mode": 8.0, "maximum": 11.0},
            "load_minutes": {"minimum": 7.0, "mode": 8.0, "maximum": 11.0},
        },
    ],
    "vessel_calls": [
        {
            "id": "vsl-001",
            "name": "Hudson Atlas",
            "eta_hour": 10.0,
            "export_cutoff_hours_before_eta": 8.0,
            "prestage_hours_before_eta": 4.0,
            "load_cutoff_hours_after_eta": 12.0,
            "switch_over_minutes": 45,
            "import_units": {"standard": 48, "reefer": 12, "hazardous": 8},
            "export_units": {"standard": 28, "reefer": 6, "hazardous": 2},
        },
        {
            "id": "vsl-002",
            "name": "Liberty Meridian",
            "eta_hour": 28.0,
            "export_cutoff_hours_before_eta": 8.0,
            "prestage_hours_before_eta": 5.0,
            "load_cutoff_hours_after_eta": 10.0,
            "switch_over_minutes": 45,
            "import_units": {"standard": 62, "reefer": 10, "hazardous": 4},
            "export_units": {"standard": 34, "reefer": 8, "hazardous": 3},
        },
        {
            "id": "vsl-003",
            "name": "Empire Horizon",
            "eta_hour": 46.0,
            "export_cutoff_hours_before_eta": 10.0,
            "prestage_hours_before_eta": 6.0,
            "load_cutoff_hours_after_eta": 11.0,
            "switch_over_minutes": 45,
            "import_units": {"standard": 74, "reefer": 14, "hazardous": 6},
            "export_units": {"standard": 42, "reefer": 9, "hazardous": 4},
        },
    ],
}

